### ISSUE TITLE
I unable to find the database and run it on Apache server

### ISSUE THREAD

**Issue by aadhilpm** [SouravDas25/AttendanceMS#3]

**Comment by SouravDas25** [comment]
The SQL file is in the database folder of the Laravel root directory.

**Comment by aamir1999** [comment]
how can i edit this project?
 where id html file?

**Comment by aamir1999** [comment]
![untitled](https://user-images.githubusercontent.com/35276396/42999211-7a8fe99c-8c3a-11e8-9ede-ac7fc2290077.png)
this type or error at run time

**Comment by aamir1999** [comment]
please can you update the android studio file and send me the project. Problem arises because of upgradation of android studio software.
amallick546@gmail.com
please send me the new project.

**Comment by aamir1999** [comment]
Can you update the .SQL file

**Comment by aamir1999** [comment]
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

why this error occur?
please tell me

**Comment by SouravDas25** [comment]
Check out issue #4, this may solve your issue.  
@aamir1999  from next time please create a new issue with approprite title.
