### ISSUE TITLE
Error Building Android Project

### ISSUE THREAD

**Issue by SouravDas25** [SouravDas25/AttendanceMS#4]
Error in building the android project via gradle due to change of Android Studio version.
Android Studio 3 is not supported in Attendance MS.

**Comment by SouravDas25** [comment]
Some changes have been committed to the Android App Project and have been tested accordingly, 
We used -
 - Android Studio 2.3 
 - Gradle 3.3
 - Android plugin 2.3.3
 
We do not intend to release any updates for Android Studio 3. We are not going to Support it.
We are migrating the entire App to Ionic ( updates will be released ASAP ).

**Comment by aamir1999** [comment]
Thanks!
